name: Deploy Resource Group to Azure using Terraform

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch (change as needed)

jobs:
  terraform:
    name: Deploy Resource Group using Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.0  # Specify the Terraform version you want to use

    - name: Set up Azure CLI
      uses: azure/setup-azurecli@v1
      with:
        azure-cli-version: '2.28.0'  # You can specify your Azure CLI version here

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Use the Azure credentials stored as a GitHub secret

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform
      run: terraform validate

    - name: Plan Terraform deployment
      run: terraform plan

    - name: Apply Terraform deployment
      run: terraform apply -auto-approve
